app/src/main/java/co/copperhead/pdfviewer/PdfViewer.java
Theres no need to process any item selections except for opening a document on initial app launch.
(Also deals with: "Uncaught ReferenceError: onRenderPage is not defined")
=> Do not process menu item selections when no PDF is loaded

app/src/main/assets/viewer.js, app/src/main/java/co/copperhead/pdfviewer/PdfViewer.java, app/src/main/java/co/copperhead/pdfviewer/fragment/DocumentPropertiesFragment.java, app/src/main/java/co/copperhead/pdfviewer/fragment/JumpToPageFragment.java, app/src/main/res/menu/pdf_viewer.xml, app/src/main/res/values/strings.xml
If you have any suggestions on code improvements, ping me.
=> Add option to show document properties

app/src/main/assets/viewer.js, app/src/main/java/co/copperhead/pdfviewer/PdfViewer.java, app/src/main/java/co/copperhead/pdfviewer/Utils.java, app/src/main/java/co/copperhead/pdfviewer/fragment/DocumentPropertiesFragment.java, app/src/main/java/co/copperhead/pdfviewer/loader/DocumentPropertiesLoader.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
Since AsyncTask is an anonymous inner class, there is a possibility of leaking memory, which AS 3.0 warns about, thus it's been mitigated to an AsyncTaskLoader, which is a safe wrapper around AsyncTask, and handles configuration changes itself.
=> Refactor document properties and parsing

app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java, app/src/main/java/org/grapheneos/pdfviewer/fragment/DocumentPropertiesFragment.java
Otherwise the activity won't be garbage collected and memory will be leaked.
=> Don't hold static reference to fragment

app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java, app/src/main/res/drawable/baseline_first_page_24.xml, app/src/main/res/drawable/baseline_last_page_24.xml, app/src/main/res/menu/pdf_viewer.xml, app/src/main/res/values/strings.xml
=> Add skip to first/last page option

app/src/main/assets/viewer.js, app/src/main/java/org/grapheneos/pdfviewer/GestureHelper.java, app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java
I started to improve the gesture across the app by adding a pinch to zoom gesture.
As the gesture detectors and listeners stuff will become bigger and bigger, I wrote a helper class in another file that presents a simple API.
Deferred 
- Continuous zoom
This is my first time contributing to an open-source project, so be free to criticize and advise me.
=> Add gesture support

build.gradle
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>
=> update gradle plugin version to 4.0.0

build.gradle
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>
=> bump gradle plugin version to 4.0.1

build.gradle
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>
=> bump gradle version to 4.1.1

.gitignore, app/build.gradle, app/src/main/AndroidManifest.xml
API 31 requires intents to set android:exported true or false
=> Build for API 31

app/build.gradle.kts
Signed-off-by: June <june@eridan.me>
=> update appcompat and material

app/build.gradle.kts
Signed-off-by: June <june@eridan.me>
=> solve deprecations in app build.gradle.kts

app/src/main/AndroidManifest.xml, app/src/main/java/org/grapheneos/pdfviewer/GestureHelper.java, app/src/main/java/org/grapheneos/pdfviewer/Utils.java, app/src/main/java/org/grapheneos/pdfviewer/loader/DocumentPropertiesLoader.java
Make SPAN_RATIO final
Specify `1000d` to divide as double
Replace valueOf with their respective data type functions (parseInt, parseLong)
Remove unused label in activity
=> Resolve some warnings

app/src/main/java/org/grapheneos/pdfviewer/fragment/JumpToPageFragment.java
Replaces deprecated usages of getActivity with requireActivity, replace onClick with lambda, and mark as NonNull
=> Solve some deprecations and warnings in JumpToPageFragment.java

app/build.gradle.kts, app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java
Provides null safety and type safety
=> Use view binding instead of findViewById

app/src/main/java/org/grapheneos/pdfviewer/PdfViewer.java, app/src/main/res/drawable/ic_error_outline_24dp.xml, app/src/main/res/layout/pdfviewer.xml, app/src/main/res/values/strings.xml
Disable the open document menu item and show the user a relevant view.
=> Handle out-of-date WebView

app/src/main/java/app/grapheneos/pdfviewer/PdfViewer.java, app/src/main/res/drawable/ic_share_24dp.xml, app/src/main/res/menu/pdf_viewer.xml, app/src/main/res/values/strings.xml
This PR adds support to share an opened pdf document.
+ Share Icon Asset
+ New options menu item "Share"
=> Share-Support

app/build.gradle.kts
BuildSDK bump already in #216.
=> Bump dependencies

app/src/main/AndroidManifest.xml, app/src/main/java/app/grapheneos/pdfviewer/App.kt, app/src/main/java/app/grapheneos/pdfviewer/PdfViewer.java, app/src/main/java/app/grapheneos/pdfviewer/ktx/View.kt, app/src/main/res/layout/pdfviewer.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values/styles.xml
- Use dynamic color on supported devices
- fix navigation bar color issue on three button navigation setting (on api 28). [before](https://i.postimg.cc/brQvK2Mx/before.png) vs [after](https://i.postimg.cc/HLcdqy8r/after.png)
=> Ui improvements 

app/src/main/java/app/grapheneos/pdfviewer/KtUtils.kt, app/src/main/java/app/grapheneos/pdfviewer/PdfViewer.java, app/src/main/java/app/grapheneos/pdfviewer/Utils.java, app/src/main/java/app/grapheneos/pdfviewer/ktx/View.kt, app/src/main/java/app/grapheneos/pdfviewer/loader/DocumentPropertiesLoader.java
tested on android 13 (real device), android 10 & 8 (on emulator)
=> bugfixes (based on google play android vitals report)

app/src/main/java/app/grapheneos/pdfviewer/PdfViewer.java
Replace app name in toolbar with the document name if it's available. Close #217.
=> Add document name in toolbar
